/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/building.glb 
Author: randum (https://sketchfab.com/randum)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/parametric-high-rise-building-e6188bfc730b4d1092e34392ca25dc13
Title: Parametric high-rise building
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/building.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.114}>
        <mesh geometry={nodes.Beta_0_0.geometry} material={materials.Fanse} />
        <mesh geometry={nodes.Beta_1_0.geometry} material={materials.Fanse} />
        <mesh geometry={nodes.Beta_2_0.geometry} material={materials.Fanse} />
        <mesh geometry={nodes.Beta_3_0.geometry} material={materials.Fanse} />
        <mesh geometry={nodes.Beta_4_0.geometry} material={materials.Fanse} />
        <mesh geometry={nodes.Beta_5_0.geometry} material={materials.Fanse} />
        <mesh geometry={nodes.Beta_6_0.geometry} material={materials.Fanse} />
        <mesh geometry={nodes.Beta_7_0.geometry} material={materials.Fanse} />
        <mesh geometry={nodes.Beta_8_0.geometry} material={materials.Fanse} />
        <mesh geometry={nodes.Beta_9_0.geometry} material={materials.Fanse} />
        <mesh geometry={nodes.Beta_10_0.geometry} material={materials.Fanse} />
        <mesh geometry={nodes.Beta_11_0.geometry} material={materials.Fanse} />
        <mesh geometry={nodes.Beta_12_0.geometry} material={materials.Fanse} />
        <mesh geometry={nodes.Beta_13_0.geometry} material={materials.Fanse} />
        <mesh geometry={nodes.Beta_14_0.geometry} material={materials.Fanse} />
        <mesh geometry={nodes.Beta_15_0.geometry} material={materials.Fanse} />
        <mesh geometry={nodes.Beta_16_0.geometry} material={materials.Fanse} />
        <mesh geometry={nodes.Beta_17_0.geometry} material={materials.Fanse} />
        <mesh geometry={nodes.Beta_18_0.geometry} material={materials.Fanse} />
        <mesh geometry={nodes.Beta_19_0.geometry} material={materials.Fanse} />
        <mesh geometry={nodes.Beta_20_0.geometry} material={materials.Fanse} />
        <mesh geometry={nodes.Gamma_0_0.geometry} material={materials.Stages} />
        <mesh geometry={nodes.Epsilon_0_0.geometry} material={materials.window} />
        <mesh geometry={nodes.Delta_0_0.geometry} material={materials.Cover} />
        <mesh geometry={nodes.Delta_0_0_1.geometry} material={materials.Cover} />
        <mesh geometry={nodes.Zeta_0_0.geometry} material={materials.Base} />
      </group>
    </group>
  )
}

useGLTF.preload('/building.glb')
